version: '3.3'
services:
    develop_env:
        container_name: develop_env
        hostname: ali-dev
        ports:
#            - '6901:6901'
            - '23:22'
        environment:
            - VNC_PW=password
            #- CONTAINERS_FOLDER=/devenv/ #NOT WORKING
        privileged: true
#        image: kasmweb/ubuntu-focal-dind:1.11.0
        build:
          context: .
          args:
            - DEFAULT_USER=ali

        shm_size: '2gb'
        volumes:
            - ./data/env/:/env/
            - ./data/home/:/home/ali/


networks:
  default:
    external:
       name: internet